[font]
normal.family = "JetBrainsMono Nerd Font"
size = 10.0

[scrolling]
history = 16384
multiplier = 3

[cursor]
style.shape = "Block"
style.blinking = "Never"

[selection]
save_to_clipboard = true

[colors.primary]
background = "#242424"
foreground = "#cfcfcf"

[colors.normal]
black   = "#242424"
red     = "#f62b5a"
green   = "#47b413"
yellow  = "#e3c401"
blue    = "#24acd4"
magenta = "#f2affd"
cyan    = "#13c299"
white   = "#e6e6e6"

[colors.bright]
black   = "#616161"
red     = "#ff4d51"
green   = "#35d450"
yellow  = "#e9e836"
blue    = "#5dc5f8"
magenta = "#feabf2"
cyan    = "#24dfc4"
white   = "#ffffff"
