general:
    startup_commands: ["shell-exec zebar"]
    shutdown_commands: []
    config_reload_commands: []
    focus_follows_cursor: true

workspaces:
    - name: "1"
    - name: "2"
    - name: "3"
    - name: "4"
    - name: "5"
    - name: "6"
    - name: "7"
    - name: "8"
    - name: "9"
    - name: "10"

gaps:
    scale_with_dpi: true
    inner_gap: "20px"
    outer_gap:
        top: "20px"
        bottom: "20px"
        right: "20px"
        left: "20px"


window_effects:
    focused_window:
        border:
            enabled: true
            color: "#8dbcff"



keybindings:
    # Activate next window in a given direction
    - commands: ['focus --direction left']
      bindings: ['lwin+left']
    - commands: ['focus --direction right']
      bindings: ['lwin+right']
    - commands: ['focus --direction up']
      bindings: ['lwin+up']
    - commands: ['focus --direction down']
      bindings: ['lwin+down']

    # Move current window in a given direction
    - commands: ['move --direction left']
      bindings: ['lwin+shift+left']
    - commands: ['move --direction right']
      bindings: ['lwin+shift+right']
    - commands: ['move --direction up']
      bindings: ['lwin+shift+up']
    - commands: ['move --direction down']
      bindings: ['lwin+shift+down']

     # Toggle tiling direction
    - commands: ['toggle-tiling-direction']
      bindings: ['lwin+v']

    # Toggle fullscreen
    - commands: ['toggle-fullscreen']
      bindings: ['lwin+f']

    # Close current window
    - commands: ['close']
      bindings: ['lwin+shift+q']

    # Switch workspace
    - commands: ['focus --workspace 1']
      bindings: ['lwin+1']
    - commands: ['focus --workspace 2']
      bindings: ['lwin+2']
    - commands: ['focus --workspace 3']
      bindings: ['lwin+3']
    - commands: ['focus --workspace 4']
      bindings: ['lwin+4']
    - commands: ['focus --workspace 5']
      bindings: ['lwin+5']
    - commands: ['focus --workspace 6']
      bindings: ['lwin+6']
    - commands: ['focus --workspace 7']
      bindings: ['lwin+7']
    - commands: ['focus --workspace 8']
      bindings: ['lwin+8']
    - commands: ['focus --workspace 9']
      bindings: ['lwin+9']
    - commands: ['focus --workspace 10']
      bindings: ['lwin+0']

    # Move current window to another workspace
    - commands: ['move --workspace 1', 'focus --workspace 1']
      bindings: ['lwin+shift+1']
    - commands: ['move --workspace 2', 'focus --workspace 2']
      bindings: ['lwin+shift+2']
    - commands: ['move --workspace 3', 'focus --workspace 3']
      bindings: ['lwin+shift+3']
    - commands: ['move --workspace 4', 'focus --workspace 4']
      bindings: ['lwin+shift+4']
    - commands: ['move --workspace 5', 'focus --workspace 5']
      bindings: ['lwin+shift+5']
    - commands: ['move --workspace 6', 'focus --workspace 6']
      bindings: ['lwin+shift+6']
    - commands: ['move --workspace 7', 'focus --workspace 7']
      bindings: ['lwin+shift+7']
    - commands: ['move --workspace 8', 'focus --workspace 8']
      bindings: ['lwin+shift+8']
    - commands: ['move --workspace 9', 'focus --workspace 9']
      bindings: ['lwin+shift+9']
    - commands: ['move --workspace 10', 'focus --workspace 10']
      bindings: ['lwin+shift+0']

    # Open Programs
    - command: "shell-exec alacritty"
      bindings: ["lwin+enter"]
    - command: "shell-exec outlook"
      bindings: ["lwin+m"]
    - command: "shell-exec firefox"
      bindings: ["lwin+b"]
    - command: "shell-exec Flow.Launcher"
      bindings: ["lwin+e"]

